Repository codefeedr/codefeedr, pull requests merged in 2018-05, with the labels that each got.

#14 Add a DAG for creating pipelines
  .bettercodehub.yml
  src/main/scala/org/codefeedr/DirectedAcyclicGraph.scala
  src/main/scala/org/codefeedr/Main.scala
  src/main/scala/org/codefeedr/keymanager/KeyManager.scala
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  src/main/scala/org/codefeedr/pipeline/PipelineType.scala
  src/main/scala/org/codefeedr/pipeline/RuntimeType.scala
  src/test/scala/org/codefeedr/DirectedAcyclicGraphTest.scala
  src/test/scala/org/codefeedr/keymanager/KeyManagerTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
Labels: not ready

#21 Improve pipeline system
  README.md
  src/main/scala/org/codefeedr/Main.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  src/main/scala/org/codefeedr/pipeline/buffer/BufferFactory.scala
  src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/BufferFactoryTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/serialization/SerializerTest.scala
  src/test/scala/org/codefeedr/testUtils/PipelineObjects.scala
Labels: pipeline

#29 Should fix the bug when a Kafka topic is consumed before it is created.
  containers/kafka/docker-compose-single-broker.yml
  src/main/scala/org/codefeedr/pipeline/buffer/KafkaBuffer.scala
  src/test/scala/org/codefeedr/pipeline/buffer/KafkaBufferTest.scala
Labels: bug

#36 Feature/logsource
  src/main/scala/org/codefeedr/plugins/log/ApacheAccessLogItem.scala
  src/main/scala/org/codefeedr/plugins/log/ApacheLogFileSource.scala
  src/test/resources/access.log
  src/test/scala/org/codefeedr/plugins/StringCollectSink.scala
  src/test/scala/org/codefeedr/plugins/log/LogSourceTest.scala
  src/test/scala/org/codefeedr/plugins/rss/RSSItemSourceTest.scala
Labels: examples

#30 Avro Schema exposure
  build.sbt
  src/main/scala/org/codefeedr/pipeline/buffer/Exceptions.scala
  src/main/scala/org/codefeedr/pipeline/buffer/KafkaBuffer.scala
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/AvroSerde.scala
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/RedisSchemaExposer.scala
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/SchemaExposer.scala
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/ZookeeperSchemaExposer.scala
  src/test/scala/org/codefeedr/pipeline/PipelineTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/KafkaBufferTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/RedisSchemaExposerTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/SchemaExposerTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/serialization/schema_exposure/ZookeeperSchemaExposerTest.scala
Labels: pipeline

#38 Fix addParents and more
  src/main/scala/org/codefeedr/DirectedAcyclicGraph.scala
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObjectList.scala
  src/test/scala/org/codefeedr/DirectedAcyclicGraphTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineObjectListTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineObjectTest.scala
  src/test/scala/org/codefeedr/pipeline/SourceTest.scala
Labels: pipeline

#40 Remove kafka container and automate it instead
  .travis.yml
  containers/kafka/CHANGELOG.md
  containers/kafka/Dockerfile
  containers/kafka/LICENSE
  containers/kafka/README.md
  containers/kafka/broker-list.sh
  containers/kafka/create-topics.sh
  containers/kafka/docker-compose-single-broker.yml
  containers/kafka/docker-compose-swarm.yml
  containers/kafka/docker-compose.yml
  containers/kafka/download-kafka.sh
  containers/kafka/start-kafka-shell.sh
  containers/kafka/start-kafka.sh
  src/main/scala/org/codefeedr/pipeline/DirectedAcyclicGraph.scala
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObjectN.scala
  src/test/scala/org/codefeedr/pipeline/DirectedAcyclicGraphTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineObjectNTest.scala
Labels: enhancement

#42 Clean up some code. Add starting of cluster object
  src/main/scala/org/codefeedr/pipeline/DirectedAcyclicGraph.scala
  src/main/scala/org/codefeedr/pipeline/Exceptions.scala
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  src/test/scala/org/codefeedr/pipeline/PipelineTest.scala
  src/test/scala/org/codefeedr/testUtils/PipelineObjects.scala
Labels: pipeline

#45 Update naming
  src/main/scala/org/codefeedr/pipeline/InputStage.scala
  src/main/scala/org/codefeedr/pipeline/OutputStage.scala
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  src/main/scala/org/codefeedr/pipeline/TransformStage.scala
  src/main/scala/org/codefeedr/plugins/log/ApacheLogFileInputStage.scala
  src/main/scala/org/codefeedr/plugins/rss/RSSInputStage.scala
  src/test/scala/org/codefeedr/ScratchTest.scala
  src/test/scala/org/codefeedr/pipeline/InputStageTest.scala
  src/test/scala/org/codefeedr/pipeline/JobTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
  src/test/scala/org/codefeedr/plugins/log/LogInputStageTest.scala
  src/test/scala/org/codefeedr/plugins/rss/RSSInputStageTest.scala
  src/test/scala/org/codefeedr/plugins/rss/RSSItemInputStageTest.scala
  src/test/scala/org/codefeedr/testUtils/PipelineObjects.scala
Labels: enhancement

#47 Improvement/rss
  src/main/scala/org/codefeedr/plugins/rss/RSSInputStage.scala
  src/main/scala/org/codefeedr/plugins/rss/RSSItemSource.scala
  src/main/scala/org/codefeedr/plugins/rss/RSSSource.scala
  src/test/scala/org/codefeedr/plugins/rss/RSSSourceTest.scala
Labels: enhancement, examples

#48 GitHub plugin
  build.sbt
  lib/avro4s-core_2.11.jar
  lib/avro4s-json_2.11.jar
  lib/avro4s-macros_2.11.jar
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/JSONSerde.scala
  src/main/scala/org/codefeedr/plugins/JsonPrinter.scala
  src/main/scala/org/codefeedr/plugins/github/GitHubEndpoints.scala
  src/main/scala/org/codefeedr/plugins/github/GitHubProtocol.scala
  src/main/scala/org/codefeedr/plugins/github/events/EventSource.scala
  src/main/scala/org/codefeedr/plugins/github/requests/EventService.scala
  src/main/scala/org/codefeedr/plugins/github/requests/GitHubRequest.scala
  src/main/scala/org/codefeedr/plugins/github/requests/GitHubResponse.scala
  src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToPushEvent.scala
  src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventsInput.scala
  src/main/scala/org/codefeedr/plugins/github/util/FiniteQueue.scala
  src/test/resources/sample_events.json
  src/test/scala/org/codefeedr/plugins/github/events/EventSourceTest.scala
  src/test/scala/org/codefeedr/plugins/github/requests/EventServiceTest.scala
  src/test/scala/org/codefeedr/plugins/github/requests/GitHubRequestTest.scala
  src/test/scala/org/codefeedr/plugins/github/stages/GitHubEventToPushEventTest.scala
  src/test/scala/org/codefeedr/plugins/github/stages/GitHubEventsInputTest.scala
  src/test/scala/org/codefeedr/plugins/github/util/FiniteQueueTest.scala
Labels: not ready, pipeline

#59 MongoDB stages for historic data
  .travis.yml
  build.sbt
  src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  src/main/scala/org/codefeedr/pipeline/buffer/serialization/JSONSerde.scala
  src/main/scala/org/codefeedr/plugins/mongodb/BaseMongoSink.scala
  src/main/scala/org/codefeedr/plugins/mongodb/BaseMongoSource.scala
  src/main/scala/org/codefeedr/plugins/mongodb/MongoInputStage.scala
  src/main/scala/org/codefeedr/plugins/mongodb/MongoOutputStage.scala
  src/test/scala/org/codefeedr/pipeline/JobTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineObjectNTest.scala
  src/test/scala/org/codefeedr/pipeline/PipelineObjectTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/BufferFactoryTest.scala
  src/test/scala/org/codefeedr/pipeline/buffer/KafkaBufferTest.scala
  src/test/scala/org/codefeedr/plugins/elasticsearch/ElasticSearchOutputStageTest.scala
  src/test/scala/org/codefeedr/plugins/mongodb/MongoInputOutputStageTest.scala
  src/test/scala/org/codefeedr/testUtils/PipelineObjects.scala
Labels: historical data

#76 Add logging
  build.sbt
  codefeedr-plugins/codefeedr-elasticsearch/src/main/scala/org/codefeedr/plugins/elasticsearch/stages/ElasticSearchOutput.scala
  codefeedr-plugins/codefeedr-elasticsearch/src/test/scala/org/codefeedr/plugins/elasticsearch/stages/ElasticSearchOutputTest.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/resources/log4j2.properties
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/BaseMongoSource.scala
  codefeedr-plugins/codefeedr-mongodb/src/test/scala/org/codefeedr/plugins/mongodb/stages/MongoInputOutputTest.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSInputStage.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSSource.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/stages/RSSInput.scala
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/stages/RSSInputTest.scala
  codefeedr-plugins/codefeedr-weblogs/src/main/scala/org/codefeedr/plugins/weblogs/stages/HttpdLogInput.scala
  codefeedr-plugins/codefeedr-weblogs/src/test/scala/org/codefeedr/plugins/weblogs/HttpdLogInputStageTest.scala
  codefeedr-plugins/codefeedr-weblogs/src/test/scala/org/codefeedr/plugins/weblogs/stages/HttpdLogInputTest.scala
Labels: enhancement

#81 Add RabbitMQ buffer and stages
  .travis.yml
  build.sbt
  codefeedr-core/src/main/scala/org/codefeedr/buffer/Buffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/BufferFactory.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/BufferType.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/KafkaBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/RabbitMQBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQOutput.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/RabbitMQBufferTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/PipelineTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/rabbitmq/RabbitMQInputOutputTest.scala
Labels: pipeline

#82 Added a duplicate filter
  .github/PULL_REQUEST_TEMPLATE.md
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/DuplicateService.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/FiniteQueue.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/utilities/DuplicateServiceTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/utilities/FiniteQueueTest.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/requests/EventService.scala
  codefeedr-plugins/codefeedr-github/src/test/scala/org/codefeedr/plugins/github/requests/EventServiceTest.scala
Labels: enhancement

#88 Feature/travis new structure
  .gitignore
  build.sbt
  codefeedr-core/src/main/scala/org/codefeedr/keymanager/StaticKeyManager.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/TravisProtocol.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/stages/TravisFilterActiveReposTransformStage.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/stages/TravisPushEventBuildInfoTransformStage.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/util/TravisBuildCollector.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/util/TravisExceptions.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/util/TravisService.scala
  codefeedr-plugins/codefeedr-travis/src/test/resources/codefeedr_build
  codefeedr-plugins/codefeedr-travis/src/test/resources/codefeedr_builds
  codefeedr-plugins/codefeedr-travis/src/test/resources/codefeedr_repo
  codefeedr-plugins/codefeedr-travis/src/test/resources/not_json_parsable
  codefeedr-plugins/codefeedr-travis/src/test/resources/repo_not_found
  codefeedr-plugins/codefeedr-travis/src/test/resources/sample_events.json
  codefeedr-plugins/codefeedr-travis/src/test/resources/single_push_event.json
  codefeedr-plugins/codefeedr-travis/src/test/resources/single_push_event_build.json
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/stages/TravisFilterActiveReposTransformStageTest.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/stages/TravisPushEventBuildInfoTransformStageTest.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/util/TravisBuildCollectorTest.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/util/TravisServiceTest.scala
Labels: examples

#92 Improvement/date refactor
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/AvroSerde.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/KafkaBufferTest.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/GitHubProtocol.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToIssueCommentEvent.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToIssuesEvent.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubIssueCommentDelay.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/MongoQuery.scala
  codefeedr-plugins/codefeedr-mongodb/src/test/scala/org/codefeedr/plugins/mongodb/stages/MongoInputOutputTest.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSItem.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSSource.scala
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/RSSSourceTest.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/TravisProtocol.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/util/TravisBuildCollector.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/util/TravisBuildCollectorTest.scala
  codefeedr-plugins/codefeedr-weblogs/src/main/scala/org/codefeedr/plugins/weblogs/HttpdLogItem.scala
  codefeedr-plugins/codefeedr-weblogs/src/main/scala/org/codefeedr/plugins/weblogs/stages/HttpdLogInput.scala
  codefeedr-plugins/codefeedr-weblogs/src/test/scala/org/codefeedr/plugins/weblogs/stages/HttpdLogInputTest.scala
Labels: enhancement

#94 Add documentation system within GIT
  .gitignore
  README.md
  build.sbt
  docs/core/buffers.md
  docs/core/key-manager.md
  docs/core/mongo-key-manager.md
  docs/core/pipeline.md
  docs/core/redis-key-manager.md
  docs/getting_started.md
  docs/index.md
  docs/logo.png
  docs/plugins/historic-data.md
  docs/plugins/plugin-examples.md
  docs/requirements.txt
  docs/theme/404.html
  docs/theme/__init__.py
  docs/theme/assets/images/favicon.ico
  docs/theme/assets/images/favicon.png
  docs/theme/assets/images/icons/bitbucket-670608a71a.svg
  docs/theme/assets/images/icons/github-1da075986e.svg
  docs/theme/assets/images/icons/gitlab-5ad3f9f9e5.svg
  docs/theme/assets/javascripts/application-ae2e7c9801.js
  docs/theme/assets/javascripts/modernizr-56ade86843.js
  docs/theme/assets/stylesheets/application-60987dc207.css
  docs/theme/assets/stylesheets/application-a9490fa5b9.css
  docs/theme/assets/stylesheets/application-f78e5cb881.palette.css
  docs/theme/base.html
  docs/theme/main.html
  docs/theme/partials/disqus.html
  docs/theme/partials/footer.html
  docs/theme/partials/header.html
  docs/theme/partials/language.html
  docs/theme/partials/nav-item.html
  docs/theme/partials/nav.html
  docs/theme/partials/search.html
  docs/theme/partials/social.html
  docs/theme/partials/source.html
  docs/theme/partials/tabs-item.html
  docs/theme/partials/tabs.html
  docs/theme/partials/toc-item.html
  docs/theme/partials/toc.html
  mkdocs.yml
Labels: documentation
