Repository codefeedr/codefeedr, pull requests merged in 2018-06, with the labels that each got.

#104 Abstracted the exponential timeout from GitHub and made Travis use it…
  build.sbt
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/HttpRequester.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/requests/GitHubRequest.scala
  codefeedr-plugins/codefeedr-github/src/test/scala/org/codefeedr/plugins/github/requests/GitHubRequestTest.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/util/TravisService.scala
Labels: enhancement

#108 [core] Added name to pipeline.
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/PipelineBuilderTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/PipelineTest.scala
Labels: not ready

#111 [core] Use overwritten ID also for sink subject. Fixes #100
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
Labels: bug

#109 Added all properties provided to a kafka buffer to getKafkaProperties()
  codefeedr-core/src/main/scala/org/codefeedr/buffer/KafkaBuffer.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/KafkaBufferTest.scala
Labels: enhancement, high-priority

#120 Replaced PipelineItem with Serializable with AnyRef
  codefeedr-core/src/main/scala/org/codefeedr/buffer/Buffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/BufferFactory.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/KafkaBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/RabbitMQBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/AbstractSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/BsonSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/JSONSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/KryoSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/Serializer.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObjectList.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObjectN.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Types.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/InputStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/OutputStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/TransformStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/kafka/KafkaInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/kafka/KafkaOutput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQOutput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/JsonPrinterOutput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/PrinterOutput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/SeqInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/StringInput.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/KafkaBufferTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/serialization/SerializerTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/CollectSink.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/kafka/KafkaInputOutputTest.scala
  codefeedr-plugins/codefeedr-elasticsearch/src/main/scala/org/codefeedr/plugins/elasticsearch/stages/ElasticSearchOutput.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/GitHubProtocol.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubIssueCommentDelay.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/stages/MongoInput.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/stages/MongoOutput.scala
  codefeedr-plugins/codefeedr-mongodb/src/test/scala/org/codefeedr/plugins/mongodb/stages/MongoInputOutputTest.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSItem.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/TravisProtocol.scala
  codefeedr-plugins/codefeedr-twitter/src/main/scala/org/codefeedr/plugin/twitter/TwitterProtocol.scala
  codefeedr-plugins/codefeedr-weblogs/src/main/scala/org/codefeedr/plugins/weblogs/HttpdLogItem.scala
Labels: enhancement

#122 Improvement/travis
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/stages/TravisFilterActiveReposTransformStage.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/stages/TravisPushEventBuildInfoTransformStage.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/stages/TravisFilterActiveReposTransformStageTest.scala
  docs/plugins/apache-access-logs.md
  docs/plugins/github.md
  docs/plugins/plugin-examples.md
  docs/plugins/rss.md
  docs/plugins/travis.md
  mkdocs.yml
Labels: documentation, enhancement

#121 Added more docs
  docs/core/buffers.md
  docs/core/key-manager.md
  docs/core/pipeline.md
  docs/getting_started.md
  docs/index.md
  docs/plugins/github.md
  docs/plugins/plugins.md
  docs/plugins/travis.md
  mkdocs.yml
Labels: documentation

#110 Add orchestration tools
  build.sbt
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Exceptions.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/PipelineTest.scala
  docs/orchestration/docker.md
  docs/orchestration/tool.md
  mkdocs.yml
  tools/docker/docker-compose-elk.yml
  tools/docker/docker-compose.yml
  tools/flink-cluster/cf-flink.py
Labels: not ready

#125 [docs] Better plugins intro
  docs/plugins/plugins.md
  mkdocs.yml
Labels: documentation

#131 Refactored RssSource to use the HttpRequester + updated tests
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/Http.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSSource.scala
  codefeedr-plugins/codefeedr-rss/src/test/resources/RSSItemSourceTestResponsesWithEmptyLine
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/RSSSourceTest.scala
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/stages/RSSInputTest.scala
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/testUtils/PipelineObjects.scala
Labels: enhancement

#137 Improve Imports
  codefeedr-core/src/main/scala/org/codefeedr/buffer/BufferFactory.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/KafkaBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/RabbitMQBuffer.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/BsonSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/KryoSerde.scala
  codefeedr-core/src/main/scala/org/codefeedr/buffer/serialization/schema_exposure/ZookeeperSchemaExposer.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/Pipeline.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineBuilder.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObject.scala
  codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObjectN.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/InputStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/OutputStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/TransformStage.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/kafka/KafkaInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQInput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/rabbitmq/RabbitMQOutput.scala
  codefeedr-core/src/main/scala/org/codefeedr/stages/utilities/PrinterOutput.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/KafkaBufferTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/RabbitMQBufferTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/buffer/serialization/schema_exposure/SchemaExposerTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/pipeline/PipelineObjectTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/kafka/KafkaInputOutputTest.scala
  codefeedr-core/src/test/scala/org/codefeedr/stages/rabbitmq/RabbitMQInputOutputTest.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/GitHubProtocol.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/requests/EventService.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/requests/GitHubRequest.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToIssueCommentEvent.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToIssuesEvent.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventToPushEvent.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubEventsInput.scala
  codefeedr-plugins/codefeedr-github/src/main/scala/org/codefeedr/plugins/github/stages/GitHubIssueCommentDelay.scala
  codefeedr-plugins/codefeedr-github/src/test/scala/org/codefeedr/plugins/github/requests/GitHubRequestTest.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/BaseMongoSink.scala
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/keymanager/MongoKeyManager.scala
  codefeedr-plugins/codefeedr-mongodb/src/test/scala/org/codefeedr/plugins/mongodb/stages/MongoInputOutputTest.scala
  codefeedr-plugins/codefeedr-rss/src/main/scala/org/codefeedr/plugins/rss/RSSSource.scala
  codefeedr-plugins/codefeedr-rss/src/test/scala/org/codefeedr/plugins/rss/RSSSourceTest.scala
  codefeedr-plugins/codefeedr-travis/src/main/scala/org/codefeedr/plugins/travis/stages/TravisPushEventBuildInfoTransformStage.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/stages/TravisFilterActiveReposTransformStageTest.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/stages/TravisPushEventBuildInfoTransformStageTest.scala
  codefeedr-plugins/codefeedr-travis/src/test/scala/org/codefeedr/plugins/travis/util/TravisBuildCollectorTest.scala
Labels: enhancement

#144 Made MongoKeyManager serializable
  codefeedr-plugins/codefeedr-mongodb/src/main/scala/org/codefeedr/plugins/mongodb/keymanager/MongoKeyManager.scala
  codefeedr-plugins/codefeedr-mongodb/src/test/scala/org/codefeedr/plugins/mongodb/keymanager/MongoKeyManagerTest.scala
Labels: bug
